### ISSUE TITLE
Fasta format

### ISSUE THREAD

**Issue by felipetraj** [Mirmu/ParalogMatching.jl#14]
Dear Mirmu

I am having difficulties in using ParalogeMatching. The installation appears to be successful, and I  think that my fasta files have an erroneous format. Could you please upload or share a test alignment to confirm the installation is ok and have a look at the header of each sequence?

thanks in advance

best

Felipe

PS: here is the error I am getting

AB, match = paralog_matching("A.fasta", "B.fasta", "Match_AB.fasta.gz");
ERROR: inconsistent inputs
Stacktrace:
 [1] #read_fasta_alignment#5(::Void, ::Function, ::String, ::Float64) at /export/home/.julia/v0.6/ParalogMatching/src/readdata.jl:70
 [2] #paralog_matching#52(::Int64, ::Int64, ::String, ::Float64, ::GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP, ::Function, ::String, ::String, ::String) at /export/home/.julia/v0.6/ParalogMatching/src/matching_fasta.jl:235
 [3] paralog_matching(::String, ::String, ::String) at /export/home/.julia/v0.6/ParalogMatching/src/matching_fasta.jl:235
 [4] macro expansion at ./REPL.jl:97 [inlined]
 [5] (::Base.REPL.##1#2{Base.REPL.REPLBackend})() at ./event.jl:73

**Comment by felipetraj** [comment]
Sorry, I just found what I needed in the test folder

felipe

**Comment by Mirmu** [comment]
Ok :) if you still need help, send me one of your fasta files and I'll give
you the corresponding regular expression to parse it properly.
Kind regards,

Thomas

Il 9 dic 2017 3:40 PM, "felipetraj" <notifications@github.com> ha scritto:

**Comment by felipetraj** [comment]
Hi Thomas

I am still unable to run it, using similar type of header as the test files and using the modified runtest.jl script...so it seems to be something else. 

ERROR: LoadError: inconsistent inputs
Stacktrace:
 [1] #read_fasta_alignment#5(::Void, ::Function, ::String, ::Float64) at /home/.julia/v0.6/ParalogMatching/src/readdata.jl:70
 [2] #paralog_matching#52(::Int64, ::Int64, ::String, ::Float64, ::GLPKMathProgInterface.GLPKInterfaceLP.GLPKSolverLP, ::Function, ::String, ::String, ::String) at /home/.julia/v0.6/ParalogMatching/src/matching_fasta.jl:235
 [3] (::ParalogMatching.#kw##paralog_matching)(::Array{Any,1}, ::ParalogMatching.#paralog_matching, ::String, ::String, ::String) at ./<missing>:0
 [4] test() at /home/ParalogMatching/runtests.jl:15
while loading /home/ParalogMatching/runtests.jl, in expression starting on line 52

How can  I send you the files

thanks 

felipe

**Comment by Mirmu** [comment]
Just send me a reduced fasta file with the first ten and last ten lines of
the original one, for both fasta that you want to match.
I will check what triggers the inconsistent input.
Best,

Thomas

Il 9 dic 2017 6:32 PM, "felipetraj" <notifications@github.com> ha scritto:

**Comment by felipetraj** [comment]
**First_10lines_1.Fasta**
>tr|1A0A1M4N6J4|1A0A1M4N6J4_9CLOT/425-489
-KDDFLAVISHELKTPLNGIIGLTEGLLSn--------------kAEHLSEE--------
------------------YNEDLL--LINHSARRLANLVEDILVFSKL---
>tr|2A0A1M4N6J4|2A0A1M4N6J4_9CLOT/851-920
-KTEFFTNISHELRTPLNVISSTLQLLESl-------------epTRQLGDES-------
------------------IKRYLK--IMHNNCYRLLRLINNIIDISRLDEG
>tr|1M3FAE6|1M3FAE6_LEPBO/209-274
-KSQFFANVSHELRTPLTLIIGPTRTLLK----------------DQKISATQ-------
-------------------RAFLE--TIERNSYTLLKHVNDLLDLSKLEAG
>tr|2M3FAE6|2M3FAE6_LEPBO/609-671

**Last_10lines_1.Fasta**
RVRRLSRG------
>tr|C9V769|C9V769_BRUNE/140-196
-----------EVSQPLVAIEISASAGRRWLAQSPPnneRAAAAIERISADSHRAIeilD
RVRRLSRG------
>tr|D7H5I7|D7H5I7_BRUAO/140-196
-----------EVSQPLVAIEISASAGRRWLAQSPPnneRAAAAIERISADSHRAIeilD
RVRRLSRG------
>tr|A0A1H2GAD2|A0A1H2GAD2_9PSED/290-343
------------LGAPLSVIDGRARRLQTSLSDDP----QQQRQLEGIRDQVARLT---R
TVRQLLDYCRPAA-

**First_10lines_2.Fasta**
>tr|10M3GZE8|10M3GZE8_LEPBO/99-206
LLIV-EDDLKFA----S----IL-LKQAN------E--KGF-----------R-GI---S
AA---T-G-E-DG---L--V--L-A---------RKHK-------------PHAILLDLD
LPG---M------DGHAV-LN-EL--KADQs------vRH---IPV-HIIS--AK-----
EYSL--KLI--RDG--AVEYIKKPV-NKKQLDEA--
>tr|11M3GZE8|11M3GZE8_LEPBO/221-323
LLII-EDDENSR----R----TT-RKLIG------N--DDV-----------K-CF---E
AS---S-G-K-EA---L--S--V-Y---------SENH-------------FDCIVLDIG
LPD---M------SGFDL-IR-EM--EKIKe------kQI---PPI-IIYT--GREL--T
KEES--KEL--QEY--SESIIIKGI-----------

**Last_10lines_2.Fasta**
>tr|K6DR17|K6DR17_9BACI/6-114
-LIA-DRDLNER----E----GL-KWLLKt----sS--IAV-----S-----E-IF---L
AA---T-Y-Q-EF---I--V--T-F---------EKES-------------PDIVLLELD
MIS---K------EEWSG-FR-DL--MQIY-------------DPI-LLLS-sAEAT--F
EKAR--LAI--DMQ--ALDLMIKPF-STTKVKS---
>tr|M6TDA6|M6TDA6_LEPIR/1-61
------------------------------------------------------------
------------------------------------------------------------
MPG---M------NGWEF-LE-EY--KKLDqe----lqTS---TLI-IMLT--TSDN--P
DDKN--KFS--QFG-sSSDFKTKPL-TNTMID----

**Comment by Mirmu** [comment]
Maybe I am mistaken, but your alignments do not seem aligned.
in A.fasta.txt, the first sequences are 111 amino-acids long, while the
last are only 74 a.a long.

You need to provide equal size sequences along the whole MSA. Here I
believe there is some problem because the last sequences of A.fasta do not
correspond very much to the initial ones. B does not have such problem.

Independently of this problem, coevolution analysis relies very much (alas)
on high quality alignements. You could easily destroy the correlations by
miss-aligning too much. For that reason, it is preferable to align only
columns that exhibit a strong signal. I see you have lower cases letters on
some columns, and quite a lot of inserts. I don't know which alignments you
use, but weakly conserved columns can be filtered away for example. Also
columns that contain more that 50% of inserts and so on.

Let me know if you have further questions !
Best,

Thomas

2017-12-09 19:16 GMT+01:00 felipetraj <notifications@github.com>:

**Comment by felipetraj** [comment]
great! I fix that, it was a problem with only 4 sequences in 4000

and now is running but it end with:

Recomputing the model
done
ERROR: LoadError: GZip.GZError(-1, "gzopen failed")
Stacktrace:
 [1] gzopen(::String, ::String, ::Int64) at /export/home/.julia/v0.6/GZip/src/GZip.jl:250
 [2] FastaIO.FastaReader{String}(::String) at /export/home/.julia/v0.6/FastaIO/src/FastaIO.jl:48
 [3] FastaIO.FastaReader(::FastaIO.##1#2, ::String, ::Type{T} where T) at /export/home/.julia/v0.6/FastaIO/src/FastaIO.jl:110
 [4] test() at /home/ParalogMatching/runtests.jl:19
while loading /home/ParalogMatching/runtests.jl, in expression starting on line 52

**Comment by Mirmu** [comment]
It means that GZip is unable to open your file (in this case, it is the
alignment called outfile_ok in the test file, that you have not provided).

Now that you have fixed your MSA, do not modify the test routine, which is
meant to check if your install is properly working, by writing in the Julia
REPL:

julia> Using ParalogMatching
julia> Pkg.test("ParalogMatching")

If it passes, it is fine.

As for your analysis, you should rather run the main command of the paralog
matching routine doing:

julia>paralog_matching("fastaA","fastaB","output")

as explained in the docs. You can then check by hand -if you are worried-
that the output contains a fasta that concatenates the sequences of FastaA
and FastaB within each species.
Best,

Thomas



2017-12-09 20:46 GMT+01:00 felipetraj <notifications@github.com>:

**Comment by yazhinia** [comment]
I am also encountering same error. 
ERROR: inconsistent inputs
I have used the command `X1=read_fasta_alignment("CUS1_H_Pfam_metgnme_combined.fa", header_regex=r"^([^_]+)_([^/]+)/")`
I have also checked length of the alignment. All sequences have same length. My ids are vary for each sequence but the pattern-wise they are consistent. 
What would be wrong here. My file is attached here.
[CUS1_H_Pfam_metgnme_combined_fa.txt](https://github.com/Mirmu/ParalogMatching.jl/files/1625404/CUS1_H_Pfam_metgnme_combined_fa.txt)


Thanks in adavnce

**Comment by pagnani** [comment]
If you take the 
>F4JJM1_ARATH/173-313
------------------------------a-RPDVVE--V-WDATSADPKL----LVFL
KSYRNTVPVPRHW--SQKRK-----YLQgnyikrd--rnvcdnhGKR-GIEK-Q-PFHLP
--DFIA-ATGIEKIRQ------------------AYI--EKEDGK------KLK--QKQR
ERMQP-K-M-G-K-----M------DIDYQ-VLHDAFFKYQT-------KP----KLSAL
GDL-----------------YFEGKE----------------------------------
-
There are lowercase letters that should not be there. Alignments are either uppercase or "-". Typically from from PFAM you should remove inserts "." and lowercase letters.
