### ISSUE TITLE
Write_fasta_match: Not able to write output file 

### ISSUE THREAD

**Issue by yazhinia** [Mirmu/ParalogMatching.jl#15]
I am trying to run low-level interface approach to perform ParalogMatching. At last step, while writing an output file I get an error like as follows:
"Closest candidates are:
  write_fasta_match(::ParalogMatching.HarmonizedAlignments, ::Array{Int64,1}, ::AbstractString)"

Commands, I used
`
X1=read_fasta_alignment("YSF3_K_Pfam.fa.gz"; header_regex=r"^([^_]+)_([^/]+)/")
 X2=read_fasta_alignment("RDS3_K_Pfam.fa.gz"; header_regex=r"^([^_]+)_([^/]+)/")
match=prepare_alignments(X1, X2)`
`
matched=run_matching(match::HarmonizedAlignments;batch = 1,strategy = "covariation")
 write_fasta_match(matched::ParalogMatching.HarmonizedAlignments,match::Vector{Int};outfile::AbstractString)
`
for write_fasta_match I have tried by simply giving this command `write_fasta_match(matched)`. The errow would be same or "ERROR: TypeError: typeassert: expected ParalogMatching.HarmonizedAlignments, got Array{Int64,1}"
I could not figure out how to overcome this issue.

Thanks in advance

**Comment by Mirmu** [comment]
`prepare_alignment` returns the modified fasta, while `run_matching` just returns the matching array between those two alignments. `write_fasta_match` just collects those and returns the concatenated pasta obtained from them, written into the output file, called outfile.

I believe you have those inputs switched, and you are using an incorrect semicolon for the outfile. Try instead with:
`write_fasta_match(match,matched,outfile)`
and tell me if the errors subsists.

PS: You probably know it, but to use the default parameters such as "covariation" and batch=1, you can use the higher level `paralog_matching`

**Comment by yazhinia** [comment]
In both appraoch, I am getting error like this: "ERROR: UndefVarError: outfile not defined".
Do I have to incorporate few other add-ons? Very perplexed what would be the reason.

**Comment by pagnani** [comment]
1.  Try to run each single command separately so that we can figure out what's going on.
2. Semicolon should not be used so for instance:
```
X1=read_fasta_alignment("YSF3_K_Pfam.fa.gz", header_regex=r"^([^_]+)_([^/]+)/")
``` ( and not using a semicolon as you did)

3. it seems to me that `outfile` is nowhere defined. It should be a string containing the name of the output file. So, for instance you could:
```
write_fasta_match(match,matched,"outfilename.fasta")
```
Strings in julia can be defined as with "".

**Comment by yazhinia** [comment]
Excellent. It worked. The error was with semicolon. Even if I give **outfile** within double quotes, due to semicolon I get all these error like **typeassert**. In ParalogMatching.ji documentation, semicolon is given within a command and I just used without changing into comma. Now It is working. 

Thank you

**Comment by pagnani** [comment]
Paralog matching considers only pairs of protein families. If you are interested interactions between, say, 3 families you can try to match 1-2, 1-3, 2-3.
